# ArgoCD: projects-infra
source: https://github.com/fseidler/helm-charts.git
release: apps
applications:
# #################################################################
#
#  base-aws-dev
#
# #################################################################
  - name: aws-dev-cadence
    source_ref: main
    enabled: true
    source_path: common/cadence
    destination: default
    helm_values:
      - ../../aws/dev/apps/cadence/values.yaml
