# ArgoCD: projects-infra
source: https://github.com/fseidler/helm-charts.git
team: prod
release: infra
applications:
# #################################################################
#
#  base-aws-dev
#
# #################################################################
  - name: base-aws-dev-apps
    source_ref: main
    enabled: true
    source_path: aws/dev/apps
    destination: default
    helm_values:
      - values.yaml
